config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  resources :users do 
    resources :bottleshots
    get '/orders' => 'bottleshots#orders'
  end

  get 'site/home'

  root 'site#home'

  namespace :admin do
    resources :glass_colors, :label_finishes, :paperstocks, :capsules, :wine_colors, :bottle_shapes 
  end

end

app/models/add_on.rb
class AddOn < ActiveRecord::Base
  has_many :add_on_bottleshots
  has_many :bottleshots, through: :add_on_bottleshots
end

app/models/add_on_bottleshot.rb
class AddOnBottleshot < ActiveRecord::Base
  belongs_to :bottleshot
  belongs_to :add_on
  
end

app/models/bottle_shape.rb
class BottleShape < ActiveRecord::Base
  has_many :bottleshots

  validates_presence_of :name

end

app/models/bottleshot.rb
class Bottleshot < ActiveRecord::Base
  belongs_to :user
  belongs_to :bottle_shape
  belongs_to :glass_color
  belongs_to :wine_color
  belongs_to :capsule
  belongs_to :paperstock
  belongs_to :label_finish

  has_many :add_on_bottleshots
  has_many :add_ons, through: :add_on_bottleshots
  accepts_nested_attributes_for :add_ons

  validates_presence_of :varietal

  def add_ons_attributes=(add_ons_attributes)
    add_ons_attributes.values.each do |add_on_attribute|
      add_on = AddOn.find_or_create_by(add_on_attribute)
      self.add_ons << add_on
    end
  end

  def fullname
    "#{self.vintage.to_s} #{self.varietal}"
  end

  def win
    
  end

  def bottle_shape_name
    self.bottle_shape.name if self.bottle_shape
  end

  def glass_color_name
    self.glass_color.name if self.glass_color
  end

  def wine_color_name
    self.wine_color.name if self.wine_color
  end

  def capsule_name
    self.capsule.name if self.capsule
  end

  def paperstock_name
    self.glass_color.name if self.glass_color
  end

  def label_finish_name
    self.label_finish.name if self.label_finish
  end

  def add_on_names
    self.add_ons.map {|add_on| add_on.name } if self.add_ons
  end

  def self.find_open_order
    where("status = ?", "open order")
  end

end

app/models/capsule.rb
class Capsule < ActiveRecord::Base
  has_many :bottleshots
  validates_presence_of :name
end

app/models/glass_color.rb
class GlassColor < ActiveRecord::Base
  has_many :bottleshots
  validates_presence_of :name
end

app/models/label_finish.rb
class LabelFinish < ActiveRecord::Base
  has_many :bottleshots
  validates_presence_of :name
end

app/models/paperstock.rb
class Paperstock < ActiveRecord::Base
  has_many :bottleshots
  validates_presence_of :name
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable, :omniauth_providers => [:google_oauth2]
  enum role: [:user, :admin]
  has_many :bottleshots
  has_many :bottle_shapes, through: :bottleshots

  def full_address
    "#{self.address_1} #{self.address_2} #{self.city} #{self.state} #{self.country} #{self.zipcode}"
  end

  def self.from_omniauth(access_token)
    data = access_token.info
    user = User.where(:email => data["email"]).first
     unless user
         user = User.create(name: data["name"],
            email: data["email"],
            password: Devise.friendly_token[0,20]
         )
     end
    user
  end

  def bottle_shapes_names
    self.bottle_shapes.map {|shape| shape.name}
  end

end

app/models/wine_color.rb
class WineColor < ActiveRecord::Base
  has_many :bottleshots

end

app/controllers/bottleshots_controller.rb
class BottleshotsController < ApplicationController

  before_action :find_user
  before_action :set_bottleshot, only: [:show, :edit, :update, :destroy]

  def index
    @bottleshots = @user.bottleshots
    @bottleshot = Bottleshot.new
    respond_to do |format|
      format.html {render :index}
      format.json {render json: @bottleshots}
    end
  end

  def show
    respond_to do |format|
      format.html {render :show}
      format.json {render json: @bottleshot}
    end
  end

  def new
    @bottleshot = Bottleshot.new
  end

  def create
    @bottleshot = @user.bottleshots.build(bottleshot_params)
    if @bottleshot.save
      render json: @bottleshot, status: 201
    else
      render 'bottleshots/new'
    end

  end

  def edit

  end

  def update
    @bottleshot.update(bottleshot_params)
    redirect_to user_bottleshots_path(@user)
  end

  def destroy
    @bottleshot.destroy
    redirect_to user_bottleshots_path(@user)
  end

  def orders
    @bottleshots = @user.bottleshots.find_open_order
  end

  private

  def find_user
    @user = User.find(params[:user_id])
  end

  def set_bottleshot
    @bottleshot = @user.bottleshots.find_by(id: params[:id])
  end

  def bottleshot_params
    params.require(:bottleshot).permit(:varietal, :vintage, :bottle_shape_id, :glass_color_id, :wine_color_id, :capsule_id, :screenprinted, :paperstock_id, :label_finish_id, :label_file, add_on_ids:[], add_ons_attributes: [:name])
  end

end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #before_action :authenticate_user!
  before_action :set_user, only: [:index, :show, :edit, :update]

  def show
    authorize @user
    respond_to do |format|
      format.html { render :show}
      format.json { render json: @user}
    end
  end

  def edit
    
  end

  def update
    authorize @user
    @user.update(user_params)
    redirect_to user_path(@user)
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :company, :website, :address_1, :address_2, :city, :state, :country, :zipcode, :telephone)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bottle_shapes_helper.rb
module BottleShapesHelper
end

app/helpers/bottleshots_helper.rb
module BottleshotsHelper
end

app/helpers/capsules_helper.rb
module CapsulesHelper
end

app/helpers/glass_colors_helper.rb
module GlassColorsHelper
end

app/helpers/label_finishes_helper.rb
module LabelFinishesHelper
end

app/helpers/paperstocks_helper.rb
module PaperstocksHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def bottle_shapes_names
    
  end
end

app/helpers/wine_colors_helper.rb
module WineColorsHelper
end

app/views/bottleshots/_form.html.erb
<div class="col-md-12">
  <%= form_for([@user, @bottleshot], html: {:class => 'form-horizontal'})  do |f| %>
      <% if @bottleshot.errors.any? %>
        <% @bottleshot.errors.each do |message| %>
          <p class="notice"><%= message %> can't be blank</p>
        <% end %>
      <% end %>
    <div class="row">
      <div class="col-md-4"></div>
      <div class="col-md-4">
        <div class="">
          <div class="field input-group form-group">
            <h5><%= f.label :varietal, "Varietal Name: "%> <%= f.text_field :varietal %></h5>     
          </div>
          <div class="field input-group form-group">
            <h5><%= f.label :vintage, "Vintage Year: "%> <%= f.number_field :vintage %></h5>
          </div> 
          <div class="field input-group form-group">       
            <h5><%= f.check_box :screenprinted %> <%= f.label :screenprinted, "  Check If Your Label Screenprinted" %></h5>
          </div>
          <div class="field input-group form-group">
            <h5><%= f.label :label_file, "URL To Label File: "%> <%= f.text_field :label_file %></h5>
          </div>  
        </div>
      </div>
      <div class="col-md-4"></div>
    </div>

    <div class="row">
      <div class="field input-group form-group radio col-md-4">
        <h5><%= f.label :bottle_shape_id, "Choose Your Bottle Shape: " %></h5>
        <ul>
          <%= f.collection_radio_buttons(:bottle_shape_id, BottleShape.all, :id, :name) do |b| %>
            <li><%= b.radio_button %><%= b.label class:"label-radio" %></li>
          <% end %>
        </ul>
      </div>
      <div class="field input-group form-group radio col-md-4">
        <ul>
          <h5><%= f.label :glass_color_id, "Choose Your Glass Color: " %></h5>
          <%= f.collection_radio_buttons(:glass_color_id, GlassColor.all, :id, :name) do |b| %>
            <li><%= b.radio_button %><%= b.label class:"label-radio" %></li>
          <% end %>
        </ul>
      </div>
      <div class="field input-group form-group radio col-md-4">
        <ul>
          <h5><%= f.label :wine_color_id, "Choose Your Wine Color: " %></h5>
          <%= f.collection_radio_buttons(:wine_color_id, WineColor.all, :id, :name) do |b| %>
            <li><%= b.radio_button %><%= b.label class:"label-radio" %></li>
          <% end %>
        </ul>
      </div>
    </div>

    <div class="row">
      <div class="field input-group form-group radio col-md-4">
        <h5><%= f.label :capsule_id, "Choose Your Capsule: " %></h5>
        <ul>
          <%= f.collection_radio_buttons(:capsule_id, Capsule.all, :id, :name) do |b| %>
            <li><%= b.radio_button %><%= b.label class:"label-radio" %></li>
          <% end %>
        </ul>
      </div>
      <div class="field input-group form-group radio col-md-4">
        <h5><%= f.label :paperstock_id, "Choose Your Label Paperstock: " %></h5>
        <ul>
          <%= f.collection_radio_buttons(:paperstock_id, Paperstock.all, :id, :name) do |b| %>
            <li><%= b.radio_button %><%= b.label class:"label-radio" %></li>
          <% end %>
        </ul>
      </div>
      <div class="field input-group form-group radio col-md-4">
        <h5><%= f.label :label_finish_id, "Choose Your Label Finish: " %></h5>
        <ul>
          <%= f.collection_radio_buttons(:label_finish_id, LabelFinish.all, :id, :name) do |b| %>
            <li><%= b.radio_button %><%= b.label class:"label-radio" %></li>
          <% end %>
        </ul>
      </div>
    </div> 
    <div class="row">
      <div class="col-md-4"></div>
      <div class="col-md-4">
        <div class="">
          <div class="field input-group form-group">
            <h5>Choose your add-on options:</h5>
            <ul>
              <%= f.collection_check_boxes(:add_on_ids, AddOn.all, :id, :name) do |b| %>
                <li><%= b.check_box %><%= b.label class:"label-radio" %></li>
              <% end %>
            </ul>
            <!--<%= f.collection_check_boxes :add_on_ids, AddOn.all, :id, :name %>-->     
          </div>
          <div class="field input-group form-group">
            <h5>
              Or tell us your own request: 
                <%= f.fields_for :add_ons, @bottleshot.add_ons.build do |a| %>
                  <%= a.text_field :name %> 
                <% end %>
            </h5>
          </div> 
        </div>
      </div>
      <div class="col-md-4"></div>
    </div>
    <center><%= f.submit class: "btn btn-primary btn-lg" %></center>
  <% end %>
</div>

app/views/bottleshots/edit.html.erb
<div class="row">
  <div class="col-md-12">
    <h1>Edit your bottleshot information:</h1>
    <%= render 'bottleshots/form' %>
  </div>
</div>

app/views/bottleshots/index.html.erb
<div class="row">
  <div class="col-md-12">
    <h1>My Library</h1>
  </div>
</div>
<div class="row">
  <div class="col-md-8">

    <h3>All of my bottle shots</h3>

    <ul id="bottleshot-index" data-user-id="<%= @user.id %>"></ul>

    <!--<form method="get" action="<%=new_user_bottleshot_path(@user)%>">
        <button type="submit">Add A New Bottleshot</button>
    </form>-->

  </div>
  <div class="col-md-4">
    <%= render "layouts/user_control_panel"%>
  </div>
</div>

<div class="row">
  <center><button class="btn btn-primary" type="button" id="showMeAwesome">
    New bottle shot please!
  </button></center>
  <div class="awesomeModal">
    <%= render 'bottleshots/form' %>
  </div>
</div>

<script type="text/javascript">
  $( document ).ready(function() {
    var userId = parseInt($("#bottleshot-index").attr("data-user-id"))
    var modal = $(".awesomeModal")[0]

    $("#showMeAwesome").on('click', function() {
      if (modal.style.display !== 'block') {
        modal.style.display = 'block';
      } else {
        modal.style.display = 'none';
      }
    })

    fetch("/users/" + userId + "/bottleshots.json")
      .then(parseToJSON)
      .then(appendResponseToDOM)
      .catch(logFailure)

    function parseToJSON(response) {
      return response.json()
    }

    function appendResponseToDOM(json) {
      var element = $("#bottleshot-index")
      for (var i = 0; i < json.length; i++) {
        var bottleshot = new Bottleshot(json[i])
        bottleshot.appendToDOM(element, userId)
      }
    }

    function logFailure(error) {
      console.log("HTTP JSON request error is : ", error)
    }

    $("form").on("submit", function(event) {
      event.preventDefault();
      var values = $(this).serialize()
      var posting = $.post("/users/" + userId + "/bottleshots", values)
      posting.done(function(data) {
        var newBottleshot = new Bottleshot(data)
        var element = $("#bottleshot-index")
        newBottleshot.appendToDOM(element, userId)
      })
    })
  });
</script>

app/views/bottleshots/new.html.erb
<div class="row">
  <div class="col-md-12">
    <h1>Order a new bottleshot:</h1>
    <%= render 'bottleshots/form' %>
  </div>
  <div class="col-md-12" id="new-bottleshot" data-user-id="<%= @user.id %>">
    <h2>New bottle shot is: </h2>
    <div><h3 class="bottleshot-name"></h3></div>
  </div>

  <script type="text/javascript" charset="utf-8">
    $(function() {
      $("form").on("submit", function(event) {
        event.preventDefault();
        var userId = parseInt($("#new-bottleshot").attr("data-user-id"))
        var values = $(this).serialize()
        var posting = $.post("/users/" + userId + "/bottleshots", values)
        posting.done(function(data) {
          $(".bottleshot-name").text(data["vintage"] + " ")
          $(".bottleshot-name").append(data["varietal"])
        })
      })
    })

  </script>

</div>

app/views/bottleshots/orders.html.erb
<div class="row">
    <div class="col-md-12">
    <h1>My Orders</h1>
  </div>
</div>
<div class="row">
  <div class="col-md-8">
    <h3>My latest orders:</h3>
    <ul>
      <% @bottleshots.each do |bottleshot| %>
        <li><%= link_to bottleshot.fullname, user_bottleshot_path(@user, bottleshot) %></li>
      <% end %>
    </ul>
    <form method="get" action="<%=new_user_bottleshot_path(@user)%>">
        <button type="submit">Create a new order</button>
    </form>
  </div>
  <div class="col-md-4">
    <%= render "layouts/user_control_panel"%>
  </div>
</div>

app/views/bottleshots/show.html.erb
<div class="row">
    <div class="col-md-12">
    <h1>Bottle shot information</h1>
  </div>
</div>
<div class="row">
  <div class="col-md-8">
    <div><h3 class="bottleshot-name"></h3></div>
    <div>Bottle Shape: <span class="bottle-shape"></span></div>
    <div>Glass Color: <span class="glass-color"></span></div>
    <div>Wine Color: <span class="wine-color"></span></div>
    <div>Capsule: <span class="capsule"></span></div>
    <div>Screenprinted: <span class="screenprinted"></span></div>
    <div>Paperstock: <span class="paperstock"></span></div>
    <div>Label Finish: <span class="label-finish"></span></div>
    <div>Label File: <span class="label-file"></span></div>
    <div>Add On Options: <span class="add-on"></span></div>

    <div class="edit-bottleshot">
      <% if @bottleshot.status == "open order" %>
        <button class="btn btn-primary btn-md">
          <%=link_to "Delete", user_bottleshot_path(@user, @bottleshot), method: "DELETE" %>
        </button>
        <button class="btn btn-primary btn-md">
          <%=link_to "Edit", edit_user_bottleshot_path(@user, @bottleshot) %>
        </button>
      <% end %>
    </div>
    <button class="next-bottleshot btn btn-primary btn-md" data-id="<%= @bottleshot.id %>" data-user-id="<%= @bottleshot.user.id %>" >Next</button>
  </div>
  <div class="col-md-4">
    <%= render "layouts/user_control_panel"%>
  </div>
</div>
<script type="text/javascript">
  $( document ).ready(function() {
    var id = parseInt($(".next-bottleshot").attr("data-id"))
    var userId = parseInt($(".next-bottleshot").attr("data-user-id"))

    fetch(`/users/${userId}/bottleshots/${id}.json`)
      .then(parseToJSON)
      .then(appendResponseToDOM)
      .catch(logFailure)

    function parseToJSON(response) {
      return response.json()
    }

    function appendResponseToDOM(json) {
      var bottleshot = new Bottleshot(json)
      bottleshot.appendBottleInfoToDOM()
      $(".next-bottleshot").attr("data-id", bottleshot.id)
    }

    $(".next-bottleshot").on("click", function () {
      var nextId = parseInt($(".next-bottleshot").attr("data-id")) + 1
      var userId = parseInt($(".next-bottleshot").attr("data-user-id"))
      fetch(`/users/${userId}/bottleshots/${nextId}.json`)
        .then(parseToJSON)
        .then(appendResponseToDOM)
        .catch(logFailure)
    })
  });
</script>