config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  resources :users do 
    resources :bottleshots
    get '/orders' => 'bottleshots#orders'
  end

  get 'site/home'

  root 'site#home'

  namespace :admin do
    resources :glass_colors, :label_finishes, :paperstocks, :capsules, :wine_colors, :bottle_shapes 
  end

end

app/models/add_on.rb
class AddOn < ActiveRecord::Base
  has_many :add_on_bottleshots
  has_many :bottleshots, through: :add_on_bottleshots
end

app/models/add_on_bottleshot.rb
class AddOnBottleshot < ActiveRecord::Base
  belongs_to :bottleshot
  belongs_to :add_on
  
end

app/models/bottle_shape.rb
class BottleShape < ActiveRecord::Base
  has_many :bottleshots

  validates_presence_of :name

end

app/models/bottleshot.rb
class Bottleshot < ActiveRecord::Base
  belongs_to :user
  belongs_to :bottle_shape
  belongs_to :glass_color
  belongs_to :wine_color
  belongs_to :capsule
  belongs_to :paperstock
  belongs_to :label_finish

  has_many :add_on_bottleshots
  has_many :add_ons, through: :add_on_bottleshots
  accepts_nested_attributes_for :add_ons

  validates_presence_of :varietal

  def add_ons_attributes=(add_ons_attributes)
    add_ons_attributes.values.each do |add_on_attribute|
      add_on = AddOn.find_or_create_by(add_on_attribute)
      self.add_ons << add_on
    end
  end

  def fullname
    "#{self.vintage.to_s} #{self.varietal}"
  end

  def win
    
  end

  def bottle_shape_name
    self.bottle_shape.name if self.bottle_shape
  end

  def glass_color_name
    self.glass_color.name if self.glass_color
  end

  def wine_color_name
    self.wine_color.name if self.wine_color
  end

  def capsule_name
    self.capsule.name if self.capsule
  end

  def paperstock_name
    self.glass_color.name if self.glass_color
  end

  def label_finish_name
    self.label_finish.name if self.label_finish
  end

  def add_on_names
    self.add_ons.map {|add_on| add_on.name } if self.add_ons
  end

  def self.find_open_order
    where("status = ?", "open order")
  end

end

app/models/capsule.rb
class Capsule < ActiveRecord::Base
  has_many :bottleshots
  validates_presence_of :name
end

app/models/glass_color.rb
class GlassColor < ActiveRecord::Base
  has_many :bottleshots
  validates_presence_of :name
end

app/models/label_finish.rb
class LabelFinish < ActiveRecord::Base
  has_many :bottleshots
  validates_presence_of :name
end

app/models/paperstock.rb
class Paperstock < ActiveRecord::Base
  has_many :bottleshots
  validates_presence_of :name
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable, :omniauth_providers => [:google_oauth2]
  enum role: [:user, :admin]
  has_many :bottleshots
  has_many :bottle_shapes, through: :bottleshots

  def full_address
    "#{self.address_1} #{self.address_2} #{self.city} #{self.state} #{self.country} #{self.zipcode}"
  end

  def self.from_omniauth(access_token)
    data = access_token.info
    user = User.where(:email => data["email"]).first
     unless user
         user = User.create(name: data["name"],
            email: data["email"],
            password: Devise.friendly_token[0,20]
         )
     end
    user
  end

  def bottle_shapes_names
    self.bottle_shapes.map {|shape| shape.name}
  end

end

app/models/wine_color.rb
class WineColor < ActiveRecord::Base
  has_many :bottleshots

end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #before_action :authenticate_user!
  before_action :set_user, only: [:index, :show, :edit, :update]

  def show
    authorize @user
    respond_to do |format|
      format.html { render :show}
      format.json { render json: @user}
    end
  end

  def edit
    
  end

  def update
    authorize @user
    @user.update(user_params)
    redirect_to user_path(@user)
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :company, :website, :address_1, :address_2, :city, :state, :country, :zipcode, :telephone)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bottle_shapes_helper.rb
module BottleShapesHelper
end

app/helpers/bottleshots_helper.rb
module BottleshotsHelper
end

app/helpers/capsules_helper.rb
module CapsulesHelper
end

app/helpers/glass_colors_helper.rb
module GlassColorsHelper
end

app/helpers/label_finishes_helper.rb
module LabelFinishesHelper
end

app/helpers/paperstocks_helper.rb
module PaperstocksHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def bottle_shapes_names
    
  end
end

app/helpers/wine_colors_helper.rb
module WineColorsHelper
end

app/views/site/_admin_home_view.html.erb
<div class="row">
  <div class="col-md-12">
    <h1>Control Panel</h1>
  </div>
</div>
<div class="row">
  <div class="col-lg-6">
    <div class="control-panel-home">
      <center><h3>Manage users</h3></center>
      <ul>
        <li>View all users</li>
        <li>View all open orders</li>
      </ul>
    </div>
  </div>

  <div class="col-lg-6">
    <div class="control-panel-home">
      <center><h3>Manage assets</h3></center>
      <ul>
        <li><%= link_to "All Bottle Shapes", admin_bottle_shapes_path %></li>
        <li><%= link_to "All Glass Colors", admin_glass_colors_path %></li>
        <li><%= link_to "All Wine Colors", admin_wine_colors_path %></li>
        <li><%= link_to "All Capsules", admin_capsules_path %></li>
        <li><%= link_to "All Paperstocks", admin_paperstocks_path %></li>
        <li><%= link_to "All Label Finishes", admin_label_finishes_path %></li>
      </ul>
    </div>
  </div>
</div>

app/views/site/_guest_home_view.html.erb
<div class="row">
  <div class="col-md-2"></div>
  <div class="col-md-8 wrapper">
    <h1>Oops! You have to be logged in to continue!</h1>
  </div>
  <div class="col-md-2"></div>
</div>
<div class="row">
  <div class="col-md-3"></div>
  <div class="col-md-3">
    <a href="<%=new_user_registration_path%>">
      <center><button type="button" class="btn btn-primary btn-lg">Sign Up</button></center>
    </a>
  </div>
  <div class="col-md-3">
    <a href="<%=new_user_session_path%>">
      <center><button type="button" class="btn btn-primary btn-lg">Sign In</button></center>
    </a>
  </div>
  <div class="col-md-3"></div>
</div>

app/views/site/_user_home_view.html.erb
<div class="row">
  <div class="col-md-12">
    <h1>Hi <%=current_user.name%>, welcome to your page!</h1>
  </div>
</div>
<div class="row">
  <div class="col-md-8">
    <div class="user account-overview">
    <h3><str>Account overview:</str></h3> 
        <div>
          <p>All my bottle shapes:</p>
          <ul>
          <% current_user.bottle_shapes_names.each do |shape_name| %>
            <li><%= shape_name %></li>
          <% end %>
          </ul>
        </div>
    </div>
  </div>
  <div class="col-md-4">
    <%= render "layouts/user_control_panel"%>
  </div>
</div>

app/views/site/home.html.erb
<% if user_signed_in? && current_user.admin? %>
  <%= render 'site/admin_home_view'%>
<% elsif user_signed_in? && current_user.user? %>
  <%= render 'site/user_home_view'%>
<% else %>
  <%= render 'site/guest_home_view'%>
<% end %>