config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  resources :users do 
    resources :bottleshots
    get '/orders' => 'bottleshots#orders'
  end

  get 'site/home'

  root 'site#home'

  namespace :admin do
    resources :glass_colors, :label_finishes, :paperstocks, :capsules, :wine_colors, :bottle_shapes 
  end

end

app/models/add_on.rb
class AddOn < ActiveRecord::Base
  has_many :add_on_bottleshots
  has_many :bottleshots, through: :add_on_bottleshots
end

app/models/add_on_bottleshot.rb
class AddOnBottleshot < ActiveRecord::Base
  belongs_to :bottleshot
  belongs_to :add_on
  
end

app/models/bottle_shape.rb
class BottleShape < ActiveRecord::Base
  has_many :bottleshots

  validates_presence_of :name

end

app/models/bottleshot.rb
class Bottleshot < ActiveRecord::Base
  belongs_to :user
  belongs_to :bottle_shape
  belongs_to :glass_color
  belongs_to :wine_color
  belongs_to :capsule
  belongs_to :paperstock
  belongs_to :label_finish

  has_many :add_on_bottleshots
  has_many :add_ons, through: :add_on_bottleshots
  accepts_nested_attributes_for :add_ons

  validates_presence_of :varietal

  def add_ons_attributes=(add_ons_attributes)
    add_ons_attributes.values.each do |add_on_attribute|
      add_on = AddOn.find_or_create_by(add_on_attribute)
      self.add_ons << add_on
    end
  end

  def fullname
    "#{self.vintage.to_s} #{self.varietal}"
  end

  def win
    
  end

  def bottle_shape_name
    self.bottle_shape.name if self.bottle_shape
  end

  def glass_color_name
    self.glass_color.name if self.glass_color
  end

  def wine_color_name
    self.wine_color.name if self.wine_color
  end

  def capsule_name
    self.capsule.name if self.capsule
  end

  def paperstock_name
    self.glass_color.name if self.glass_color
  end

  def label_finish_name
    self.label_finish.name if self.label_finish
  end

  def add_on_names
    self.add_ons.map {|add_on| add_on.name } if self.add_ons
  end

  def self.find_open_order
    where("status = ?", "open order")
  end

end

app/models/capsule.rb
class Capsule < ActiveRecord::Base
  has_many :bottleshots
  validates_presence_of :name
end

app/models/glass_color.rb
class GlassColor < ActiveRecord::Base
  has_many :bottleshots
  validates_presence_of :name
end

app/models/label_finish.rb
class LabelFinish < ActiveRecord::Base
  has_many :bottleshots
  validates_presence_of :name
end

app/models/paperstock.rb
class Paperstock < ActiveRecord::Base
  has_many :bottleshots
  validates_presence_of :name
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable, :omniauth_providers => [:google_oauth2]
  enum role: [:user, :admin]
  has_many :bottleshots
  has_many :bottle_shapes, through: :bottleshots

  def full_address
    "#{self.address_1} #{self.address_2} #{self.city} #{self.state} #{self.country} #{self.zipcode}"
  end

  def self.from_omniauth(access_token)
    data = access_token.info
    user = User.where(:email => data["email"]).first
     unless user
         user = User.create(name: data["name"],
            email: data["email"],
            password: Devise.friendly_token[0,20]
         )
     end
    user
  end

  def bottle_shapes_names
    self.bottle_shapes.map {|shape| shape.name}
  end

end

app/models/wine_color.rb
class WineColor < ActiveRecord::Base
  has_many :bottleshots

end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #before_action :authenticate_user!
  before_action :set_user, only: [:index, :show, :edit, :update]

  def show
    authorize @user
    respond_to do |format|
      format.html { render :show}
      format.json { render json: @user}
    end
  end

  def edit
    
  end

  def update
    authorize @user
    @user.update(user_params)
    redirect_to user_path(@user)
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :company, :website, :address_1, :address_2, :city, :state, :country, :zipcode, :telephone)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bottleshots_helper.rb
module BottleshotsHelper
end

app/helpers/capsules_helper.rb
module CapsulesHelper
end

app/helpers/glass_colors_helper.rb
module GlassColorsHelper
end

app/helpers/paperstocks_helper.rb
module PaperstocksHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def bottle_shapes_names
    
  end
end

app/helpers/wine_colors_helper.rb
module WineColorsHelper
end

app/views/layouts/_footer.html.erb
<div class="container">
  <nav id="secondaryNavigation">   
    <div class="footer-nav col-md-4">
      <a href="http://outshinery.com">
        <span>Outshinery Homepage</span>
      </a>
    </div> 
    <div class="footer-nav col-md-4">
      <a href="mailto:info@outshinery.com">
        <span>Email us!</span>
      </a>
    </div> 
    <div class="footer-nav col-md-4">
      <a href="http://www.lauriemillotte.com/" target="_blank">
        <span>Laurie's design work</span>
      </a>
    </div>   
  </nav>
</div>
<div id="siteInfo"><a href="mailto:info@outshinery.com" class="site-email">info@outshinery.com</a></div>

app/views/layouts/_nav_bar_fixed_to_top.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">

    <div class="navbar-header">
      <!--<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Outshinery", root_path, class: "navbar-brand" %>-->
      <div id="logoWrapper">
        <a href="<%= root_path %>">
          <div id="logoImage">
            <img src="//static1.squarespace.com/static/55e38929e4b06d04a995c0c8/t/56e4ebbc746fb91c91d2f3e1/1476475343430/?format=1500w" alt="Outshinery | Professional and consistent bottle shots before your beverage is bottled" data-pin-nopin="true">
          </div>
        </a>
      </div>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
        <%= render 'layouts/nav_links_for_auth' %> 
    </div><!--/.nav-collapse -->
  </div>
</nav>

app/views/layouts/_nav_links_for_auth.html.erb
<ul class="nav navbar-nav">
  <% if user_signed_in? %>
    <li><%= link_to "Profile", user_path(current_user) %></li>
    <li><%= link_to "Open Orders", user_orders_path(current_user) %></li>
    <li><%= link_to "Library", user_bottleshots_path(current_user) %></li>
  <% else %>
    <li><%= link_to "Sign Up", new_user_registration_path %></li>
    <li><%= link_to "Sign In", new_user_session_path %></li>
    <li><%= link_to "Sign in with Google", user_google_oauth2_omniauth_authorize_path %></li>
  <% end %> 
</ul>
<% if user_signed_in? %>
  <ul class="nav navbar-nav navbar-right">
    <li><%= link_to "Sign Out", destroy_user_session_path, method: "DELETE" %></li>
  </ul>
<% end %>

app/views/layouts/_user_control_panel.html.erb
<div class="user control-panel">
  <h3>I want to:</h3>
  <a href="#">
    <div class="option">
      View and manage my new orders
    </div>
  </a>
  <a href="#">
    <div class="option">
      Visit my bottle shot library
    </div>
  </a>
  <a href="#">
    <div class="option">
      Place a new order
    </div>
  </a>
  <a href="mailto:info@outshinery.com">
    <div class="option">
      Talk to someone at Outshinery
    </div>
  </a>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Outshinery | Professional and consistent bottle shots before your beverage is bottled</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="navigation">
    <%= render 'layouts/nav_bar_fixed_to_top' %>
  </div>   
  <div id="mainContent">
    <div class="container">
      <div class="main-wrapper">
        <br>
        <% flash.each do |key, value| %>
          <div class="alert alert-<%= key %>"><%= value %></div>
        <% end %>
        <%= yield %>
      </div>
    </div>
  </div>
  <div id="footer">
  <%= render 'layouts/footer'%>
  </div>
</body>
</html>